// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo-commerce/v3/cart/domain/cart"
	"flamingo.me/flamingo/v3/framework/web"
	mock "github.com/stretchr/testify/mock"
)

// NewCartMerger creates a new instance of CartMerger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartMerger(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartMerger {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CartMerger{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CartMerger is an autogenerated mock type for the CartMerger type
type CartMerger struct {
	mock.Mock
}

type CartMerger_Expecter struct {
	mock *mock.Mock
}

func (_m *CartMerger) EXPECT() *CartMerger_Expecter {
	return &CartMerger_Expecter{mock: &_m.Mock}
}

// Merge provides a mock function for the type CartMerger
func (_mock *CartMerger) Merge(ctx context.Context, session *web.Session, guestCart cart.Cart, customerCart cart.Cart) {
	_mock.Called(ctx, session, guestCart, customerCart)
	return
}

// CartMerger_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type CartMerger_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx context.Context
//   - session *web.Session
//   - guestCart cart.Cart
//   - customerCart cart.Cart
func (_e *CartMerger_Expecter) Merge(ctx any, session any, guestCart any, customerCart any) *CartMerger_Merge_Call {
	return &CartMerger_Merge_Call{Call: _e.mock.On("Merge", ctx, session, guestCart, customerCart)}
}

func (_c *CartMerger_Merge_Call) Run(run func(ctx context.Context, session *web.Session, guestCart cart.Cart, customerCart cart.Cart)) *CartMerger_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Session
		if args[1] != nil {
			arg1 = args[1].(*web.Session)
		}
		var arg2 cart.Cart
		if args[2] != nil {
			arg2 = args[2].(cart.Cart)
		}
		var arg3 cart.Cart
		if args[3] != nil {
			arg3 = args[3].(cart.Cart)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CartMerger_Merge_Call) Return() *CartMerger_Merge_Call {
	_c.Call.Return()
	return _c
}

func (_c *CartMerger_Merge_Call) RunAndReturn(run func(ctx context.Context, session *web.Session, guestCart cart.Cart, customerCart cart.Cart)) *CartMerger_Merge_Call {
	_c.Run(run)
	return _c
}
