// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo-commerce/v3/cart/domain/cart"
	"flamingo.me/flamingo/v3/framework/web"
	mock "github.com/stretchr/testify/mock"
)

// NewCartReceiver creates a new instance of CartReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartReceiver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CartReceiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CartReceiver is an autogenerated mock type for the Receiver type
type CartReceiver struct {
	mock.Mock
}

type CartReceiver_Expecter struct {
	mock *mock.Mock
}

func (_m *CartReceiver) EXPECT() *CartReceiver_Expecter {
	return &CartReceiver_Expecter{mock: &_m.Mock}
}

// GetCart provides a mock function for the type CartReceiver
func (_mock *CartReceiver) GetCart(ctx context.Context, session *web.Session) (*cart.Cart, cart.ModifyBehaviour, error) {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *cart.Cart
	var r1 cart.ModifyBehaviour
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) (*cart.Cart, cart.ModifyBehaviour, error)); ok {
		return returnFunc(ctx, session)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) *cart.Cart); ok {
		r0 = returnFunc(ctx, session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Session) cart.ModifyBehaviour); ok {
		r1 = returnFunc(ctx, session)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(cart.ModifyBehaviour)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *web.Session) error); ok {
		r2 = returnFunc(ctx, session)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CartReceiver_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type CartReceiver_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - session *web.Session
func (_e *CartReceiver_Expecter) GetCart(ctx any, session any) *CartReceiver_GetCart_Call {
	return &CartReceiver_GetCart_Call{Call: _e.mock.On("GetCart", ctx, session)}
}

func (_c *CartReceiver_GetCart_Call) Run(run func(ctx context.Context, session *web.Session)) *CartReceiver_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Session
		if args[1] != nil {
			arg1 = args[1].(*web.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartReceiver_GetCart_Call) Return(cart1 *cart.Cart, modifyBehaviour cart.ModifyBehaviour, err error) *CartReceiver_GetCart_Call {
	_c.Call.Return(cart1, modifyBehaviour, err)
	return _c
}

func (_c *CartReceiver_GetCart_Call) RunAndReturn(run func(ctx context.Context, session *web.Session) (*cart.Cart, cart.ModifyBehaviour, error)) *CartReceiver_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetCartWithoutCache provides a mock function for the type CartReceiver
func (_mock *CartReceiver) GetCartWithoutCache(ctx context.Context, session *web.Session) (*cart.Cart, error) {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for GetCartWithoutCache")
	}

	var r0 *cart.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) (*cart.Cart, error)); ok {
		return returnFunc(ctx, session)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) *cart.Cart); ok {
		r0 = returnFunc(ctx, session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Session) error); ok {
		r1 = returnFunc(ctx, session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CartReceiver_GetCartWithoutCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCartWithoutCache'
type CartReceiver_GetCartWithoutCache_Call struct {
	*mock.Call
}

// GetCartWithoutCache is a helper method to define mock.On call
//   - ctx context.Context
//   - session *web.Session
func (_e *CartReceiver_Expecter) GetCartWithoutCache(ctx any, session any) *CartReceiver_GetCartWithoutCache_Call {
	return &CartReceiver_GetCartWithoutCache_Call{Call: _e.mock.On("GetCartWithoutCache", ctx, session)}
}

func (_c *CartReceiver_GetCartWithoutCache_Call) Run(run func(ctx context.Context, session *web.Session)) *CartReceiver_GetCartWithoutCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Session
		if args[1] != nil {
			arg1 = args[1].(*web.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartReceiver_GetCartWithoutCache_Call) Return(cart1 *cart.Cart, err error) *CartReceiver_GetCartWithoutCache_Call {
	_c.Call.Return(cart1, err)
	return _c
}

func (_c *CartReceiver_GetCartWithoutCache_Call) RunAndReturn(run func(ctx context.Context, session *web.Session) (*cart.Cart, error)) *CartReceiver_GetCartWithoutCache_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyBehaviour provides a mock function for the type CartReceiver
func (_mock *CartReceiver) ModifyBehaviour(ctx context.Context) (cart.ModifyBehaviour, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ModifyBehaviour")
	}

	var r0 cart.ModifyBehaviour
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (cart.ModifyBehaviour, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) cart.ModifyBehaviour); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cart.ModifyBehaviour)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CartReceiver_ModifyBehaviour_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyBehaviour'
type CartReceiver_ModifyBehaviour_Call struct {
	*mock.Call
}

// ModifyBehaviour is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CartReceiver_Expecter) ModifyBehaviour(ctx any) *CartReceiver_ModifyBehaviour_Call {
	return &CartReceiver_ModifyBehaviour_Call{Call: _e.mock.On("ModifyBehaviour", ctx)}
}

func (_c *CartReceiver_ModifyBehaviour_Call) Run(run func(ctx context.Context)) *CartReceiver_ModifyBehaviour_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CartReceiver_ModifyBehaviour_Call) Return(modifyBehaviour cart.ModifyBehaviour, err error) *CartReceiver_ModifyBehaviour_Call {
	_c.Call.Return(modifyBehaviour, err)
	return _c
}

func (_c *CartReceiver_ModifyBehaviour_Call) RunAndReturn(run func(ctx context.Context) (cart.ModifyBehaviour, error)) *CartReceiver_ModifyBehaviour_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldHaveCart provides a mock function for the type CartReceiver
func (_mock *CartReceiver) ShouldHaveCart(ctx context.Context, session *web.Session) bool {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for ShouldHaveCart")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) bool); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CartReceiver_ShouldHaveCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldHaveCart'
type CartReceiver_ShouldHaveCart_Call struct {
	*mock.Call
}

// ShouldHaveCart is a helper method to define mock.On call
//   - ctx context.Context
//   - session *web.Session
func (_e *CartReceiver_Expecter) ShouldHaveCart(ctx any, session any) *CartReceiver_ShouldHaveCart_Call {
	return &CartReceiver_ShouldHaveCart_Call{Call: _e.mock.On("ShouldHaveCart", ctx, session)}
}

func (_c *CartReceiver_ShouldHaveCart_Call) Run(run func(ctx context.Context, session *web.Session)) *CartReceiver_ShouldHaveCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Session
		if args[1] != nil {
			arg1 = args[1].(*web.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartReceiver_ShouldHaveCart_Call) Return(b bool) *CartReceiver_ShouldHaveCart_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CartReceiver_ShouldHaveCart_Call) RunAndReturn(run func(ctx context.Context, session *web.Session) bool) *CartReceiver_ShouldHaveCart_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldHaveGuestCart provides a mock function for the type CartReceiver
func (_mock *CartReceiver) ShouldHaveGuestCart(session *web.Session) bool {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for ShouldHaveGuestCart")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*web.Session) bool); ok {
		r0 = returnFunc(session)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CartReceiver_ShouldHaveGuestCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldHaveGuestCart'
type CartReceiver_ShouldHaveGuestCart_Call struct {
	*mock.Call
}

// ShouldHaveGuestCart is a helper method to define mock.On call
//   - session *web.Session
func (_e *CartReceiver_Expecter) ShouldHaveGuestCart(session any) *CartReceiver_ShouldHaveGuestCart_Call {
	return &CartReceiver_ShouldHaveGuestCart_Call{Call: _e.mock.On("ShouldHaveGuestCart", session)}
}

func (_c *CartReceiver_ShouldHaveGuestCart_Call) Run(run func(session *web.Session)) *CartReceiver_ShouldHaveGuestCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *web.Session
		if args[0] != nil {
			arg0 = args[0].(*web.Session)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CartReceiver_ShouldHaveGuestCart_Call) Return(b bool) *CartReceiver_ShouldHaveGuestCart_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CartReceiver_ShouldHaveGuestCart_Call) RunAndReturn(run func(session *web.Session) bool) *CartReceiver_ShouldHaveGuestCart_Call {
	_c.Call.Return(run)
	return _c
}

// ViewCart provides a mock function for the type CartReceiver
func (_mock *CartReceiver) ViewCart(ctx context.Context, session *web.Session) (*cart.Cart, error) {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for ViewCart")
	}

	var r0 *cart.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) (*cart.Cart, error)); ok {
		return returnFunc(ctx, session)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) *cart.Cart); ok {
		r0 = returnFunc(ctx, session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Session) error); ok {
		r1 = returnFunc(ctx, session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CartReceiver_ViewCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewCart'
type CartReceiver_ViewCart_Call struct {
	*mock.Call
}

// ViewCart is a helper method to define mock.On call
//   - ctx context.Context
//   - session *web.Session
func (_e *CartReceiver_Expecter) ViewCart(ctx any, session any) *CartReceiver_ViewCart_Call {
	return &CartReceiver_ViewCart_Call{Call: _e.mock.On("ViewCart", ctx, session)}
}

func (_c *CartReceiver_ViewCart_Call) Run(run func(ctx context.Context, session *web.Session)) *CartReceiver_ViewCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Session
		if args[1] != nil {
			arg1 = args[1].(*web.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartReceiver_ViewCart_Call) Return(cart1 *cart.Cart, err error) *CartReceiver_ViewCart_Call {
	_c.Call.Return(cart1, err)
	return _c
}

func (_c *CartReceiver_ViewCart_Call) RunAndReturn(run func(ctx context.Context, session *web.Session) (*cart.Cart, error)) *CartReceiver_ViewCart_Call {
	_c.Call.Return(run)
	return _c
}

// ViewGuestCart provides a mock function for the type CartReceiver
func (_mock *CartReceiver) ViewGuestCart(ctx context.Context, session *web.Session) (*cart.Cart, error) {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for ViewGuestCart")
	}

	var r0 *cart.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) (*cart.Cart, error)); ok {
		return returnFunc(ctx, session)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session) *cart.Cart); ok {
		r0 = returnFunc(ctx, session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Session) error); ok {
		r1 = returnFunc(ctx, session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CartReceiver_ViewGuestCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewGuestCart'
type CartReceiver_ViewGuestCart_Call struct {
	*mock.Call
}

// ViewGuestCart is a helper method to define mock.On call
//   - ctx context.Context
//   - session *web.Session
func (_e *CartReceiver_Expecter) ViewGuestCart(ctx any, session any) *CartReceiver_ViewGuestCart_Call {
	return &CartReceiver_ViewGuestCart_Call{Call: _e.mock.On("ViewGuestCart", ctx, session)}
}

func (_c *CartReceiver_ViewGuestCart_Call) Run(run func(ctx context.Context, session *web.Session)) *CartReceiver_ViewGuestCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Session
		if args[1] != nil {
			arg1 = args[1].(*web.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartReceiver_ViewGuestCart_Call) Return(cart1 *cart.Cart, err error) *CartReceiver_ViewGuestCart_Call {
	_c.Call.Return(cart1, err)
	return _c
}

func (_c *CartReceiver_ViewGuestCart_Call) RunAndReturn(run func(ctx context.Context, session *web.Session) (*cart.Cart, error)) *CartReceiver_ViewGuestCart_Call {
	_c.Call.Return(run)
	return _c
}
