description: Value object to add (or increment) something into the basket
type: object
properties:
    MarketplaceCode:
        type: string
    VariantMarketplaceCode:
        type: string
    Qty:
        type: int
