language: go

go:
  - 1.x
  - 1.13.x

install: true

script:
  - set -e
  - fmt=$(gofmt -l .)
  - test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
  - go test -race -vet=all ./...
  - go run github.com/fzipp/gocyclo -top 20 .
  - go run github.com/client9/misspell/cmd/misspell -error .
  - go run github.com/gordonklaus/ineffassign .

jobs:
  allow_failures:
    - script: go run golang.org/x/lint/golint -set_exit_status $(go list ./...)
  include:
    - stage: static
      go: 1.x
      script: go run golang.org/x/lint/golint -set_exit_status $(go list ./...)
    - stage: testrecent
      go: 1.x
      script:
        # test is done only for recent version.
        # Older versions might include other files during compilation and may therefore generate different go.mod files
        - go generate ./...
        - git diff --quiet || (echo 'generated go files are not up to date, check go generate, go.sum and go.mod' ; git diff ; exit 1)
    - stage: integrationtest
      go: 1.x
      script:
        - cd test/integrationtest/projecttest && go run -tags graphql main.go && cd ../../../
        - git diff --quiet || (echo 'generated go files for graphql are not up to date, check go generate, go.sum and go.mod' ; git diff ; exit 1)
        - go test -test.count=10 -race -v ./test/integrationtest/... -tags=integration
