// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo-commerce/v3/category/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewCategoryService creates a new instance of CategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CategoryService is an autogenerated mock type for the CategoryService type
type CategoryService struct {
	mock.Mock
}

type CategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryService) EXPECT() *CategoryService_Expecter {
	return &CategoryService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type CategoryService
func (_mock *CategoryService) Get(ctx context.Context, categoryCode string) (domain.Category, error) {
	ret := _mock.Called(ctx, categoryCode)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Category, error)); ok {
		return returnFunc(ctx, categoryCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Category); ok {
		r0 = returnFunc(ctx, categoryCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, categoryCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CategoryService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryCode string
func (_e *CategoryService_Expecter) Get(ctx any, categoryCode any) *CategoryService_Get_Call {
	return &CategoryService_Get_Call{Call: _e.mock.On("Get", ctx, categoryCode)}
}

func (_c *CategoryService_Get_Call) Run(run func(ctx context.Context, categoryCode string)) *CategoryService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryService_Get_Call) Return(category domain.Category, err error) *CategoryService_Get_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *CategoryService_Get_Call) RunAndReturn(run func(ctx context.Context, categoryCode string) (domain.Category, error)) *CategoryService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Tree provides a mock function for the type CategoryService
func (_mock *CategoryService) Tree(ctx context.Context, activeCategoryCode string) (domain.Tree, error) {
	ret := _mock.Called(ctx, activeCategoryCode)

	if len(ret) == 0 {
		panic("no return value specified for Tree")
	}

	var r0 domain.Tree
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Tree, error)); ok {
		return returnFunc(ctx, activeCategoryCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Tree); ok {
		r0 = returnFunc(ctx, activeCategoryCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Tree)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, activeCategoryCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_Tree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tree'
type CategoryService_Tree_Call struct {
	*mock.Call
}

// Tree is a helper method to define mock.On call
//   - ctx context.Context
//   - activeCategoryCode string
func (_e *CategoryService_Expecter) Tree(ctx any, activeCategoryCode any) *CategoryService_Tree_Call {
	return &CategoryService_Tree_Call{Call: _e.mock.On("Tree", ctx, activeCategoryCode)}
}

func (_c *CategoryService_Tree_Call) Run(run func(ctx context.Context, activeCategoryCode string)) *CategoryService_Tree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryService_Tree_Call) Return(tree domain.Tree, err error) *CategoryService_Tree_Call {
	_c.Call.Return(tree, err)
	return _c
}

func (_c *CategoryService_Tree_Call) RunAndReturn(run func(ctx context.Context, activeCategoryCode string) (domain.Tree, error)) *CategoryService_Tree_Call {
	_c.Call.Return(run)
	return _c
}
