// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	"flamingo.me/flamingo-commerce/v3/cart/domain/cart"
	"flamingo.me/flamingo-commerce/v3/cart/domain/placeorder"
	"flamingo.me/flamingo-commerce/v3/payment/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewWebCartPaymentGateway creates a new instance of WebCartPaymentGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebCartPaymentGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebCartPaymentGateway {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &WebCartPaymentGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// WebCartPaymentGateway is an autogenerated mock type for the WebCartPaymentGateway type
type WebCartPaymentGateway struct {
	mock.Mock
}

type WebCartPaymentGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *WebCartPaymentGateway) EXPECT() *WebCartPaymentGateway_Expecter {
	return &WebCartPaymentGateway_Expecter{mock: &_m.Mock}
}

// CancelOrderPayment provides a mock function for the type WebCartPaymentGateway
func (_mock *WebCartPaymentGateway) CancelOrderPayment(ctx context.Context, cartPayment *placeorder.Payment, reason domain.CancellationReason) error {
	ret := _mock.Called(ctx, cartPayment, reason)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderPayment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *placeorder.Payment, domain.CancellationReason) error); ok {
		r0 = returnFunc(ctx, cartPayment, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebCartPaymentGateway_CancelOrderPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderPayment'
type WebCartPaymentGateway_CancelOrderPayment_Call struct {
	*mock.Call
}

// CancelOrderPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - cartPayment *placeorder.Payment
//   - reason domain.CancellationReason
func (_e *WebCartPaymentGateway_Expecter) CancelOrderPayment(ctx any, cartPayment any, reason any) *WebCartPaymentGateway_CancelOrderPayment_Call {
	return &WebCartPaymentGateway_CancelOrderPayment_Call{Call: _e.mock.On("CancelOrderPayment", ctx, cartPayment, reason)}
}

func (_c *WebCartPaymentGateway_CancelOrderPayment_Call) Run(run func(ctx context.Context, cartPayment *placeorder.Payment, reason domain.CancellationReason)) *WebCartPaymentGateway_CancelOrderPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *placeorder.Payment
		if args[1] != nil {
			arg1 = args[1].(*placeorder.Payment)
		}
		var arg2 domain.CancellationReason
		if args[2] != nil {
			arg2 = args[2].(domain.CancellationReason)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebCartPaymentGateway_CancelOrderPayment_Call) Return(err error) *WebCartPaymentGateway_CancelOrderPayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebCartPaymentGateway_CancelOrderPayment_Call) RunAndReturn(run func(ctx context.Context, cartPayment *placeorder.Payment, reason domain.CancellationReason) error) *WebCartPaymentGateway_CancelOrderPayment_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmResult provides a mock function for the type WebCartPaymentGateway
func (_mock *WebCartPaymentGateway) ConfirmResult(ctx context.Context, cart1 *cart.Cart, cartPayment *placeorder.Payment) error {
	ret := _mock.Called(ctx, cart1, cartPayment)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, *placeorder.Payment) error); ok {
		r0 = returnFunc(ctx, cart1, cartPayment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebCartPaymentGateway_ConfirmResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmResult'
type WebCartPaymentGateway_ConfirmResult_Call struct {
	*mock.Call
}

// ConfirmResult is a helper method to define mock.On call
//   - ctx context.Context
//   - cart1 *cart.Cart
//   - cartPayment *placeorder.Payment
func (_e *WebCartPaymentGateway_Expecter) ConfirmResult(ctx any, cart1 any, cartPayment any) *WebCartPaymentGateway_ConfirmResult_Call {
	return &WebCartPaymentGateway_ConfirmResult_Call{Call: _e.mock.On("ConfirmResult", ctx, cart1, cartPayment)}
}

func (_c *WebCartPaymentGateway_ConfirmResult_Call) Run(run func(ctx context.Context, cart1 *cart.Cart, cartPayment *placeorder.Payment)) *WebCartPaymentGateway_ConfirmResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cart.Cart
		if args[1] != nil {
			arg1 = args[1].(*cart.Cart)
		}
		var arg2 *placeorder.Payment
		if args[2] != nil {
			arg2 = args[2].(*placeorder.Payment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebCartPaymentGateway_ConfirmResult_Call) Return(err error) *WebCartPaymentGateway_ConfirmResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebCartPaymentGateway_ConfirmResult_Call) RunAndReturn(run func(ctx context.Context, cart1 *cart.Cart, cartPayment *placeorder.Payment) error) *WebCartPaymentGateway_ConfirmResult_Call {
	_c.Call.Return(run)
	return _c
}

// FlowStatus provides a mock function for the type WebCartPaymentGateway
func (_mock *WebCartPaymentGateway) FlowStatus(ctx context.Context, cart1 *cart.Cart, correlationID string) (*domain.FlowStatus, error) {
	ret := _mock.Called(ctx, cart1, correlationID)

	if len(ret) == 0 {
		panic("no return value specified for FlowStatus")
	}

	var r0 *domain.FlowStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) (*domain.FlowStatus, error)); ok {
		return returnFunc(ctx, cart1, correlationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) *domain.FlowStatus); ok {
		r0 = returnFunc(ctx, cart1, correlationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FlowStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cart.Cart, string) error); ok {
		r1 = returnFunc(ctx, cart1, correlationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WebCartPaymentGateway_FlowStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowStatus'
type WebCartPaymentGateway_FlowStatus_Call struct {
	*mock.Call
}

// FlowStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - cart1 *cart.Cart
//   - correlationID string
func (_e *WebCartPaymentGateway_Expecter) FlowStatus(ctx any, cart1 any, correlationID any) *WebCartPaymentGateway_FlowStatus_Call {
	return &WebCartPaymentGateway_FlowStatus_Call{Call: _e.mock.On("FlowStatus", ctx, cart1, correlationID)}
}

func (_c *WebCartPaymentGateway_FlowStatus_Call) Run(run func(ctx context.Context, cart1 *cart.Cart, correlationID string)) *WebCartPaymentGateway_FlowStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cart.Cart
		if args[1] != nil {
			arg1 = args[1].(*cart.Cart)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebCartPaymentGateway_FlowStatus_Call) Return(flowStatus *domain.FlowStatus, err error) *WebCartPaymentGateway_FlowStatus_Call {
	_c.Call.Return(flowStatus, err)
	return _c
}

func (_c *WebCartPaymentGateway_FlowStatus_Call) RunAndReturn(run func(ctx context.Context, cart1 *cart.Cart, correlationID string) (*domain.FlowStatus, error)) *WebCartPaymentGateway_FlowStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Methods provides a mock function for the type WebCartPaymentGateway
func (_mock *WebCartPaymentGateway) Methods() []domain.Method {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Methods")
	}

	var r0 []domain.Method
	if returnFunc, ok := ret.Get(0).(func() []domain.Method); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Method)
		}
	}
	return r0
}

// WebCartPaymentGateway_Methods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Methods'
type WebCartPaymentGateway_Methods_Call struct {
	*mock.Call
}

// Methods is a helper method to define mock.On call
func (_e *WebCartPaymentGateway_Expecter) Methods() *WebCartPaymentGateway_Methods_Call {
	return &WebCartPaymentGateway_Methods_Call{Call: _e.mock.On("Methods")}
}

func (_c *WebCartPaymentGateway_Methods_Call) Run(run func()) *WebCartPaymentGateway_Methods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WebCartPaymentGateway_Methods_Call) Return(methods []domain.Method) *WebCartPaymentGateway_Methods_Call {
	_c.Call.Return(methods)
	return _c
}

func (_c *WebCartPaymentGateway_Methods_Call) RunAndReturn(run func() []domain.Method) *WebCartPaymentGateway_Methods_Call {
	_c.Call.Return(run)
	return _c
}

// OrderPaymentFromFlow provides a mock function for the type WebCartPaymentGateway
func (_mock *WebCartPaymentGateway) OrderPaymentFromFlow(ctx context.Context, cart1 *cart.Cart, correlationID string) (*placeorder.Payment, error) {
	ret := _mock.Called(ctx, cart1, correlationID)

	if len(ret) == 0 {
		panic("no return value specified for OrderPaymentFromFlow")
	}

	var r0 *placeorder.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) (*placeorder.Payment, error)); ok {
		return returnFunc(ctx, cart1, correlationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) *placeorder.Payment); ok {
		r0 = returnFunc(ctx, cart1, correlationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*placeorder.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cart.Cart, string) error); ok {
		r1 = returnFunc(ctx, cart1, correlationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WebCartPaymentGateway_OrderPaymentFromFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderPaymentFromFlow'
type WebCartPaymentGateway_OrderPaymentFromFlow_Call struct {
	*mock.Call
}

// OrderPaymentFromFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - cart1 *cart.Cart
//   - correlationID string
func (_e *WebCartPaymentGateway_Expecter) OrderPaymentFromFlow(ctx any, cart1 any, correlationID any) *WebCartPaymentGateway_OrderPaymentFromFlow_Call {
	return &WebCartPaymentGateway_OrderPaymentFromFlow_Call{Call: _e.mock.On("OrderPaymentFromFlow", ctx, cart1, correlationID)}
}

func (_c *WebCartPaymentGateway_OrderPaymentFromFlow_Call) Run(run func(ctx context.Context, cart1 *cart.Cart, correlationID string)) *WebCartPaymentGateway_OrderPaymentFromFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cart.Cart
		if args[1] != nil {
			arg1 = args[1].(*cart.Cart)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WebCartPaymentGateway_OrderPaymentFromFlow_Call) Return(payment *placeorder.Payment, err error) *WebCartPaymentGateway_OrderPaymentFromFlow_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *WebCartPaymentGateway_OrderPaymentFromFlow_Call) RunAndReturn(run func(ctx context.Context, cart1 *cart.Cart, correlationID string) (*placeorder.Payment, error)) *WebCartPaymentGateway_OrderPaymentFromFlow_Call {
	_c.Call.Return(run)
	return _c
}

// StartFlow provides a mock function for the type WebCartPaymentGateway
func (_mock *WebCartPaymentGateway) StartFlow(ctx context.Context, cart1 *cart.Cart, correlationID string, returnURL *url.URL) (*domain.FlowResult, error) {
	ret := _mock.Called(ctx, cart1, correlationID, returnURL)

	if len(ret) == 0 {
		panic("no return value specified for StartFlow")
	}

	var r0 *domain.FlowResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string, *url.URL) (*domain.FlowResult, error)); ok {
		return returnFunc(ctx, cart1, correlationID, returnURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string, *url.URL) *domain.FlowResult); ok {
		r0 = returnFunc(ctx, cart1, correlationID, returnURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FlowResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cart.Cart, string, *url.URL) error); ok {
		r1 = returnFunc(ctx, cart1, correlationID, returnURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WebCartPaymentGateway_StartFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartFlow'
type WebCartPaymentGateway_StartFlow_Call struct {
	*mock.Call
}

// StartFlow is a helper method to define mock.On call
//   - ctx context.Context
//   - cart1 *cart.Cart
//   - correlationID string
//   - returnURL *url.URL
func (_e *WebCartPaymentGateway_Expecter) StartFlow(ctx any, cart1 any, correlationID any, returnURL any) *WebCartPaymentGateway_StartFlow_Call {
	return &WebCartPaymentGateway_StartFlow_Call{Call: _e.mock.On("StartFlow", ctx, cart1, correlationID, returnURL)}
}

func (_c *WebCartPaymentGateway_StartFlow_Call) Run(run func(ctx context.Context, cart1 *cart.Cart, correlationID string, returnURL *url.URL)) *WebCartPaymentGateway_StartFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cart.Cart
		if args[1] != nil {
			arg1 = args[1].(*cart.Cart)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *url.URL
		if args[3] != nil {
			arg3 = args[3].(*url.URL)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *WebCartPaymentGateway_StartFlow_Call) Return(flowResult *domain.FlowResult, err error) *WebCartPaymentGateway_StartFlow_Call {
	_c.Call.Return(flowResult, err)
	return _c
}

func (_c *WebCartPaymentGateway_StartFlow_Call) RunAndReturn(run func(ctx context.Context, cart1 *cart.Cart, correlationID string, returnURL *url.URL) (*domain.FlowResult, error)) *WebCartPaymentGateway_StartFlow_Call {
	_c.Call.Return(run)
	return _c
}
