// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo-commerce/v3/cart/domain/cart"
	"flamingo.me/flamingo-commerce/v3/cart/domain/decorator"
	"flamingo.me/flamingo-commerce/v3/product/domain"
	"flamingo.me/flamingo/v3/framework/web"
	mock "github.com/stretchr/testify/mock"
)

// NewItemValidator creates a new instance of ItemValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemValidator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ItemValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ItemValidator is an autogenerated mock type for the ItemValidator type
type ItemValidator struct {
	mock.Mock
}

type ItemValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *ItemValidator) EXPECT() *ItemValidator_Expecter {
	return &ItemValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type ItemValidator
func (_mock *ItemValidator) Validate(ctx context.Context, session *web.Session, cart1 *decorator.DecoratedCart, deliveryCode string, request cart.AddRequest, product domain.BasicProduct) error {
	ret := _mock.Called(ctx, session, cart1, deliveryCode, request, product)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Session, *decorator.DecoratedCart, string, cart.AddRequest, domain.BasicProduct) error); ok {
		r0 = returnFunc(ctx, session, cart1, deliveryCode, request, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ItemValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ItemValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - session *web.Session
//   - cart1 *decorator.DecoratedCart
//   - deliveryCode string
//   - request cart.AddRequest
//   - product domain.BasicProduct
func (_e *ItemValidator_Expecter) Validate(ctx any, session any, cart1 any, deliveryCode any, request any, product any) *ItemValidator_Validate_Call {
	return &ItemValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, session, cart1, deliveryCode, request, product)}
}

func (_c *ItemValidator_Validate_Call) Run(run func(ctx context.Context, session *web.Session, cart1 *decorator.DecoratedCart, deliveryCode string, request cart.AddRequest, product domain.BasicProduct)) *ItemValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Session
		if args[1] != nil {
			arg1 = args[1].(*web.Session)
		}
		var arg2 *decorator.DecoratedCart
		if args[2] != nil {
			arg2 = args[2].(*decorator.DecoratedCart)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 cart.AddRequest
		if args[4] != nil {
			arg4 = args[4].(cart.AddRequest)
		}
		var arg5 domain.BasicProduct
		if args[5] != nil {
			arg5 = args[5].(domain.BasicProduct)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ItemValidator_Validate_Call) Return(err error) *ItemValidator_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ItemValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, session *web.Session, cart1 *decorator.DecoratedCart, deliveryCode string, request cart.AddRequest, product domain.BasicProduct) error) *ItemValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
