// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "flamingo.me/flamingo-commerce/v3/customer/domain"
	mock "github.com/stretchr/testify/mock"
)

// Customer is an autogenerated mock type for the Customer type
type Customer struct {
	mock.Mock
}

// GetAddresses provides a mock function with given fields:
func (_m *Customer) GetAddresses() []domain.Address {
	ret := _m.Called()

	var r0 []domain.Address
	if rf, ok := ret.Get(0).(func() []domain.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Address)
		}
	}

	return r0
}

// GetDefaultBillingAddress provides a mock function with given fields:
func (_m *Customer) GetDefaultBillingAddress() *domain.Address {
	ret := _m.Called()

	var r0 *domain.Address
	if rf, ok := ret.Get(0).(func() *domain.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Address)
		}
	}

	return r0
}

// GetDefaultShippingAddress provides a mock function with given fields:
func (_m *Customer) GetDefaultShippingAddress() *domain.Address {
	ret := _m.Called()

	var r0 *domain.Address
	if rf, ok := ret.Get(0).(func() *domain.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Address)
		}
	}

	return r0
}

// GetID provides a mock function with given fields:
func (_m *Customer) GetID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPersonalData provides a mock function with given fields:
func (_m *Customer) GetPersonalData() domain.PersonData {
	ret := _m.Called()

	var r0 domain.PersonData
	if rf, ok := ret.Get(0).(func() domain.PersonData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.PersonData)
	}

	return r0
}
