// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo-commerce/v3/customer/domain"
	"flamingo.me/flamingo/v3/core/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewCustomerIdentityService creates a new instance of CustomerIdentityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerIdentityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerIdentityService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CustomerIdentityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CustomerIdentityService is an autogenerated mock type for the CustomerIdentityService type
type CustomerIdentityService struct {
	mock.Mock
}

type CustomerIdentityService_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerIdentityService) EXPECT() *CustomerIdentityService_Expecter {
	return &CustomerIdentityService_Expecter{mock: &_m.Mock}
}

// GetByIdentity provides a mock function for the type CustomerIdentityService
func (_mock *CustomerIdentityService) GetByIdentity(ctx context.Context, identity auth.Identity) (domain.Customer, error) {
	ret := _mock.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdentity")
	}

	var r0 domain.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Identity) (domain.Customer, error)); ok {
		return returnFunc(ctx, identity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Identity) domain.Customer); ok {
		r0 = returnFunc(ctx, identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.Identity) error); ok {
		r1 = returnFunc(ctx, identity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerIdentityService_GetByIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdentity'
type CustomerIdentityService_GetByIdentity_Call struct {
	*mock.Call
}

// GetByIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - identity auth.Identity
func (_e *CustomerIdentityService_Expecter) GetByIdentity(ctx any, identity any) *CustomerIdentityService_GetByIdentity_Call {
	return &CustomerIdentityService_GetByIdentity_Call{Call: _e.mock.On("GetByIdentity", ctx, identity)}
}

func (_c *CustomerIdentityService_GetByIdentity_Call) Run(run func(ctx context.Context, identity auth.Identity)) *CustomerIdentityService_GetByIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.Identity
		if args[1] != nil {
			arg1 = args[1].(auth.Identity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomerIdentityService_GetByIdentity_Call) Return(customer domain.Customer, err error) *CustomerIdentityService_GetByIdentity_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *CustomerIdentityService_GetByIdentity_Call) RunAndReturn(run func(ctx context.Context, identity auth.Identity) (domain.Customer, error)) *CustomerIdentityService_GetByIdentity_Call {
	_c.Call.Return(run)
	return _c
}
