// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "flamingo.me/flamingo/v3/core/auth"

	domain "flamingo.me/flamingo-commerce/v3/customer/domain"

	mock "github.com/stretchr/testify/mock"
)

// CustomerIdentityService is an autogenerated mock type for the CustomerIdentityService type
type CustomerIdentityService struct {
	mock.Mock
}

// GetByIdentity provides a mock function with given fields: ctx, identity
func (_m *CustomerIdentityService) GetByIdentity(ctx context.Context, identity auth.Identity) (domain.Customer, error) {
	ret := _m.Called(ctx, identity)

	var r0 domain.Customer
	if rf, ok := ret.Get(0).(func(context.Context, auth.Identity) domain.Customer); ok {
		r0 = rf(ctx, identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, auth.Identity) error); ok {
		r1 = rf(ctx, identity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
