// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo-commerce/v3/cart/domain/cart"
	mock "github.com/stretchr/testify/mock"
)

// NewVoucherHandler creates a new instance of VoucherHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoucherHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoucherHandler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &VoucherHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// VoucherHandler is an autogenerated mock type for the VoucherHandler type
type VoucherHandler struct {
	mock.Mock
}

type VoucherHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *VoucherHandler) EXPECT() *VoucherHandler_Expecter {
	return &VoucherHandler_Expecter{mock: &_m.Mock}
}

// ApplyVoucher provides a mock function for the type VoucherHandler
func (_mock *VoucherHandler) ApplyVoucher(ctx context.Context, cart1 *cart.Cart, couponCode string) (*cart.Cart, error) {
	ret := _mock.Called(ctx, cart1, couponCode)

	if len(ret) == 0 {
		panic("no return value specified for ApplyVoucher")
	}

	var r0 *cart.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) (*cart.Cart, error)); ok {
		return returnFunc(ctx, cart1, couponCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) *cart.Cart); ok {
		r0 = returnFunc(ctx, cart1, couponCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cart.Cart, string) error); ok {
		r1 = returnFunc(ctx, cart1, couponCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VoucherHandler_ApplyVoucher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyVoucher'
type VoucherHandler_ApplyVoucher_Call struct {
	*mock.Call
}

// ApplyVoucher is a helper method to define mock.On call
//   - ctx context.Context
//   - cart1 *cart.Cart
//   - couponCode string
func (_e *VoucherHandler_Expecter) ApplyVoucher(ctx any, cart1 any, couponCode any) *VoucherHandler_ApplyVoucher_Call {
	return &VoucherHandler_ApplyVoucher_Call{Call: _e.mock.On("ApplyVoucher", ctx, cart1, couponCode)}
}

func (_c *VoucherHandler_ApplyVoucher_Call) Run(run func(ctx context.Context, cart1 *cart.Cart, couponCode string)) *VoucherHandler_ApplyVoucher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cart.Cart
		if args[1] != nil {
			arg1 = args[1].(*cart.Cart)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VoucherHandler_ApplyVoucher_Call) Return(cart11 *cart.Cart, err error) *VoucherHandler_ApplyVoucher_Call {
	_c.Call.Return(cart11, err)
	return _c
}

func (_c *VoucherHandler_ApplyVoucher_Call) RunAndReturn(run func(ctx context.Context, cart1 *cart.Cart, couponCode string) (*cart.Cart, error)) *VoucherHandler_ApplyVoucher_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveVoucher provides a mock function for the type VoucherHandler
func (_mock *VoucherHandler) RemoveVoucher(ctx context.Context, cart1 *cart.Cart, couponCode string) (*cart.Cart, error) {
	ret := _mock.Called(ctx, cart1, couponCode)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVoucher")
	}

	var r0 *cart.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) (*cart.Cart, error)); ok {
		return returnFunc(ctx, cart1, couponCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) *cart.Cart); ok {
		r0 = returnFunc(ctx, cart1, couponCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cart.Cart, string) error); ok {
		r1 = returnFunc(ctx, cart1, couponCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VoucherHandler_RemoveVoucher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveVoucher'
type VoucherHandler_RemoveVoucher_Call struct {
	*mock.Call
}

// RemoveVoucher is a helper method to define mock.On call
//   - ctx context.Context
//   - cart1 *cart.Cart
//   - couponCode string
func (_e *VoucherHandler_Expecter) RemoveVoucher(ctx any, cart1 any, couponCode any) *VoucherHandler_RemoveVoucher_Call {
	return &VoucherHandler_RemoveVoucher_Call{Call: _e.mock.On("RemoveVoucher", ctx, cart1, couponCode)}
}

func (_c *VoucherHandler_RemoveVoucher_Call) Run(run func(ctx context.Context, cart1 *cart.Cart, couponCode string)) *VoucherHandler_RemoveVoucher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cart.Cart
		if args[1] != nil {
			arg1 = args[1].(*cart.Cart)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VoucherHandler_RemoveVoucher_Call) Return(cart11 *cart.Cart, err error) *VoucherHandler_RemoveVoucher_Call {
	_c.Call.Return(cart11, err)
	return _c
}

func (_c *VoucherHandler_RemoveVoucher_Call) RunAndReturn(run func(ctx context.Context, cart1 *cart.Cart, couponCode string) (*cart.Cart, error)) *VoucherHandler_RemoveVoucher_Call {
	_c.Call.Return(run)
	return _c
}
