// Code generated by flamingo.me/graphql DO NOT EDIT!
//go:build graphql
// +build graphql

package graphql

import "flamingo.me/dingo"

// this empty module is used by go generate to provide a dingo module because module.go is not compiled during generate
type Module struct{}

// Configure dummy method
func (Module) Configure(injector *dingo.Injector) {}
