package mocks

import (
	"flamingo.me/flamingo-commerce/v3/cart/domain/cart"
)

// AllBehaviour is an manually created mock to combine all autogenerated mocks
type AllBehaviour struct {
	CompleteBehaviour
	ModifyBehaviour
	GiftCardAndVoucherBehaviour
	GiftCardBehaviour
}

var (
	_ cart.ModifyBehaviour             = new(AllBehaviour)
	_ cart.CompleteBehaviour           = new(AllBehaviour)
	_ cart.GiftCardBehaviour           = new(AllBehaviour)
	_ cart.GiftCardAndVoucherBehaviour = new(AllBehaviour)
)
