// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo-commerce/v3/cart/domain/cart"
	mock "github.com/stretchr/testify/mock"
)

// NewGiftCardBehaviour creates a new instance of GiftCardBehaviour. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGiftCardBehaviour(t interface {
	mock.TestingT
	Cleanup(func())
}) *GiftCardBehaviour {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &GiftCardBehaviour{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// GiftCardBehaviour is an autogenerated mock type for the GiftCardBehaviour type
type GiftCardBehaviour struct {
	mock.Mock
}

type GiftCardBehaviour_Expecter struct {
	mock *mock.Mock
}

func (_m *GiftCardBehaviour) EXPECT() *GiftCardBehaviour_Expecter {
	return &GiftCardBehaviour_Expecter{mock: &_m.Mock}
}

// ApplyGiftCard provides a mock function for the type GiftCardBehaviour
func (_mock *GiftCardBehaviour) ApplyGiftCard(ctx context.Context, cart1 *cart.Cart, giftCardCode string) (*cart.Cart, cart.DeferEvents, error) {
	ret := _mock.Called(ctx, cart1, giftCardCode)

	if len(ret) == 0 {
		panic("no return value specified for ApplyGiftCard")
	}

	var r0 *cart.Cart
	var r1 cart.DeferEvents
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) (*cart.Cart, cart.DeferEvents, error)); ok {
		return returnFunc(ctx, cart1, giftCardCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) *cart.Cart); ok {
		r0 = returnFunc(ctx, cart1, giftCardCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cart.Cart, string) cart.DeferEvents); ok {
		r1 = returnFunc(ctx, cart1, giftCardCode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(cart.DeferEvents)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *cart.Cart, string) error); ok {
		r2 = returnFunc(ctx, cart1, giftCardCode)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GiftCardBehaviour_ApplyGiftCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyGiftCard'
type GiftCardBehaviour_ApplyGiftCard_Call struct {
	*mock.Call
}

// ApplyGiftCard is a helper method to define mock.On call
//   - ctx context.Context
//   - cart1 *cart.Cart
//   - giftCardCode string
func (_e *GiftCardBehaviour_Expecter) ApplyGiftCard(ctx any, cart1 any, giftCardCode any) *GiftCardBehaviour_ApplyGiftCard_Call {
	return &GiftCardBehaviour_ApplyGiftCard_Call{Call: _e.mock.On("ApplyGiftCard", ctx, cart1, giftCardCode)}
}

func (_c *GiftCardBehaviour_ApplyGiftCard_Call) Run(run func(ctx context.Context, cart1 *cart.Cart, giftCardCode string)) *GiftCardBehaviour_ApplyGiftCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cart.Cart
		if args[1] != nil {
			arg1 = args[1].(*cart.Cart)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GiftCardBehaviour_ApplyGiftCard_Call) Return(cart11 *cart.Cart, deferEvents cart.DeferEvents, err error) *GiftCardBehaviour_ApplyGiftCard_Call {
	_c.Call.Return(cart11, deferEvents, err)
	return _c
}

func (_c *GiftCardBehaviour_ApplyGiftCard_Call) RunAndReturn(run func(ctx context.Context, cart1 *cart.Cart, giftCardCode string) (*cart.Cart, cart.DeferEvents, error)) *GiftCardBehaviour_ApplyGiftCard_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGiftCard provides a mock function for the type GiftCardBehaviour
func (_mock *GiftCardBehaviour) RemoveGiftCard(ctx context.Context, cart1 *cart.Cart, giftCardCode string) (*cart.Cart, cart.DeferEvents, error) {
	ret := _mock.Called(ctx, cart1, giftCardCode)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGiftCard")
	}

	var r0 *cart.Cart
	var r1 cart.DeferEvents
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) (*cart.Cart, cart.DeferEvents, error)); ok {
		return returnFunc(ctx, cart1, giftCardCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart, string) *cart.Cart); ok {
		r0 = returnFunc(ctx, cart1, giftCardCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cart.Cart, string) cart.DeferEvents); ok {
		r1 = returnFunc(ctx, cart1, giftCardCode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(cart.DeferEvents)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *cart.Cart, string) error); ok {
		r2 = returnFunc(ctx, cart1, giftCardCode)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GiftCardBehaviour_RemoveGiftCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGiftCard'
type GiftCardBehaviour_RemoveGiftCard_Call struct {
	*mock.Call
}

// RemoveGiftCard is a helper method to define mock.On call
//   - ctx context.Context
//   - cart1 *cart.Cart
//   - giftCardCode string
func (_e *GiftCardBehaviour_Expecter) RemoveGiftCard(ctx any, cart1 any, giftCardCode any) *GiftCardBehaviour_RemoveGiftCard_Call {
	return &GiftCardBehaviour_RemoveGiftCard_Call{Call: _e.mock.On("RemoveGiftCard", ctx, cart1, giftCardCode)}
}

func (_c *GiftCardBehaviour_RemoveGiftCard_Call) Run(run func(ctx context.Context, cart1 *cart.Cart, giftCardCode string)) *GiftCardBehaviour_RemoveGiftCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cart.Cart
		if args[1] != nil {
			arg1 = args[1].(*cart.Cart)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GiftCardBehaviour_RemoveGiftCard_Call) Return(cart11 *cart.Cart, deferEvents cart.DeferEvents, err error) *GiftCardBehaviour_RemoveGiftCard_Call {
	_c.Call.Return(cart11, deferEvents, err)
	return _c
}

func (_c *GiftCardBehaviour_RemoveGiftCard_Call) RunAndReturn(run func(ctx context.Context, cart1 *cart.Cart, giftCardCode string) (*cart.Cart, cart.DeferEvents, error)) *GiftCardBehaviour_RemoveGiftCard_Call {
	_c.Call.Return(run)
	return _c
}
