// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import cart "flamingo.me/flamingo-commerce/cart/domain/cart"
import context "context"
import domain "flamingo.me/flamingo-commerce/order/domain"
import mock "github.com/stretchr/testify/mock"

// Behaviour is an autogenerated mock type for the Behaviour type
type Behaviour struct {
	mock.Mock
}

// PlaceOrder provides a mock function with given fields: ctx, _a1, payment
func (_m *Behaviour) PlaceOrder(ctx context.Context, _a1 *cart.Cart, payment *cart.CartPayment) (domain.PlacedOrderInfos, error) {
	ret := _m.Called(ctx, _a1, payment)

	var r0 domain.PlacedOrderInfos
	if rf, ok := ret.Get(0).(func(context.Context, *cart.Cart, *cart.CartPayment) domain.PlacedOrderInfos); ok {
		r0 = rf(ctx, _a1, payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.PlacedOrderInfos)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cart.Cart, *cart.CartPayment) error); ok {
		r1 = rf(ctx, _a1, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
