// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import domain "flamingo.me/flamingo-commerce/v3/order/domain"
import mock "github.com/stretchr/testify/mock"

// GuestOrderService is an autogenerated mock type for the GuestOrderService type
type GuestOrderService struct {
	mock.Mock
}

// GetBehaviour provides a mock function with given fields: _a0
func (_m *GuestOrderService) GetBehaviour(_a0 context.Context) (domain.Behaviour, error) {
	ret := _m.Called(_a0)

	var r0 domain.Behaviour
	if rf, ok := ret.Get(0).(func(context.Context) domain.Behaviour); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Behaviour)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
