// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	cart "flamingo.me/flamingo-commerce/v3/cart/domain/cart"

	domain "flamingo.me/flamingo-commerce/v3/product/domain"

	mock "github.com/stretchr/testify/mock"

	sourcingdomain "flamingo.me/flamingo-commerce/v3/sourcing/domain"
)

// AvailableSourcesProvider is an autogenerated mock type for the AvailableSourcesProvider type
type AvailableSourcesProvider struct {
	mock.Mock
}

// GetPossibleSources provides a mock function with given fields: ctx, product, deliveryInfo
func (_m *AvailableSourcesProvider) GetPossibleSources(ctx context.Context, product domain.BasicProduct, deliveryInfo *cart.DeliveryInfo) ([]sourcingdomain.Source, error) {
	ret := _m.Called(ctx, product, deliveryInfo)

	var r0 []sourcingdomain.Source
	if rf, ok := ret.Get(0).(func(context.Context, domain.BasicProduct, *cart.DeliveryInfo) []sourcingdomain.Source); ok {
		r0 = rf(ctx, product, deliveryInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sourcingdomain.Source)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.BasicProduct, *cart.DeliveryInfo) error); ok {
		r1 = rf(ctx, product, deliveryInfo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
