// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	cart "flamingo.me/flamingo-commerce/v3/cart/domain/cart"

	domain "flamingo.me/flamingo-commerce/v3/product/domain"

	mock "github.com/stretchr/testify/mock"

	sourcingdomain "flamingo.me/flamingo-commerce/v3/sourcing/domain"
)

// StockProvider is an autogenerated mock type for the StockProvider type
type StockProvider struct {
	mock.Mock
}

// GetStock provides a mock function with given fields: ctx, product, source, deliveryInfo
func (_m *StockProvider) GetStock(ctx context.Context, product domain.BasicProduct, source sourcingdomain.Source, deliveryInfo *cart.DeliveryInfo) (int, error) {
	ret := _m.Called(ctx, product, source, deliveryInfo)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, domain.BasicProduct, sourcingdomain.Source, *cart.DeliveryInfo) int); ok {
		r0 = rf(ctx, product, source, deliveryInfo)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.BasicProduct, sourcingdomain.Source, *cart.DeliveryInfo) error); ok {
		r1 = rf(ctx, product, source, deliveryInfo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
