name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      REV: $(git rev-list --topo-order origin/master..HEAD | tail -1)
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-go@v4
        with:
          go-version: 1.x
          check-latest: true
      - name: Echo start commit
        run: |
          rev=${{ env.REV }}
          if [[ $rev == '' ]]; then echo 'revision not found'; else echo used revision number: $rev; fi
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.55'
          args: $(rev=${{ env.REV }}; if [ rev != '' ]; then echo --new-from-rev=$rev; fi)
