name: golangci-lint
on:
  push:
    tags:
      - v*
    branches-ignore:
      - master
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      REV: $(git rev-list --topo-order origin/master..HEAD | tail -1)
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.*
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Echo start commit
        run: |
          echo ${{ env.REV }}
          echo $(echo 'bla')
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --new-from-rev=${{ env.REV }}
