name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: '0'

      - uses: actions/setup-go@v6
        with:
          # NOTE: we intentionally pin this job to a stable Go version because golangci-lint
          # (and some of its analyzers) may lag behind the latest Go syntax.
          go-version: '1.26'
          check-latest: true

      - name: Determine start revision for lint
        id: rev
        shell: bash
        run: |
          # finds your first commit ahead from master, then finds revision before your first commit
          # to be used as a starting point for the linter
          FIRST_COMMIT=$(git rev-list --topo-order origin/master..HEAD | tail -1)
          if [ -z "$FIRST_COMMIT" ]; then
            REV=$(git rev-parse origin/master^1)
          else
            REV=$(git rev-parse "$FIRST_COMMIT"^1)
          fi
          echo "used revision number: $REV"
          echo "rev=$REV" >> "$GITHUB_OUTPUT"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: 'v2.12.2'
          args: --new-from-rev=${{ steps.rev.outputs.rev }}

