name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.x' ]
    name: With Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test
        run: go test -race ./...
  generate-checks:
    runs-on: ubuntu-latest
    name: Generate check
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.x
          check-latest: true
      - name: Goimports
        run: |
          go run golang.org/x/tools/cmd/goimports@latest -w .
          git diff --quiet || (echo 'goimports requires code cleanup:' ; git diff ; exit 1)
      - name: Go Generate
        run: |
          go generate ./...
          # Bug in swag results in Flaky swagger docs - see https://github.com/swaggo/swag/issues/721
          # git diff --quiet  || (echo 'generated go files are not up to date, check go generate, go.sum and go.mod' ; git diff ; exit 1)
          git diff --quiet -- . ":(exclude)docs" || (echo 'generated go files are not up to date, check go generate, go.sum and go.mod' ; git diff -- . ":(exclude)docs"; exit 1)
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.x
          check-latest: true
      - name: Generate GraphQL
        run: |
          cd test/integrationtest/projecttest && go run -tags graphql main.go && cd ../../../
          git diff --quiet || (echo 'generated go files for graphql are not up to date, check go generate' ; git diff ; exit 1)
      - name: Test
        run: go test -test.count=10 -race -v ./test/integrationtest/... -tags=integration
