name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'go.mod', '1.*' ]
    name: Tests
    steps:
      - uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go != 'go.mod' && matrix.go || '' }}
          go-version-file: ${{ matrix.go == 'go.mod' && 'go.mod' || '' }}
          check-latest: true
      - name: Test
        run: CGO_ENABLED=1 go test -race ./...
  static-checks:
    runs-on: ubuntu-latest
    name: Static checks
    steps:
      - uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.*'
          check-latest: true
      - name: Go Vet
        run: go vet ./...
      - name: Go Fmt
        run: |
          fmt=$(gofmt -l .)
          test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
      - name: Goimports
        run: |
          go run golang.org/x/tools/cmd/goimports@latest -w .
          git diff --quiet || (echo 'goimports requires code cleanup:' ; git diff ; exit 1)
      - name: Go Generate
        run: |
          go generate ./...
          # Bug in swag results in Flaky swagger docs - see https://github.com/swaggo/swag/issues/721
          # git diff --quiet  || (echo 'generated go files are not up to date, check go generate, go.sum and go.mod' ; git diff ; exit 1)
          git diff --quiet -- . ":(exclude)docs" || (echo 'generated go files are not up to date, check go generate, go.sum and go.mod' ; git diff -- . ":(exclude)docs"; exit 1)
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration
    steps:
      - uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.*'
          check-latest: true
      - name: Generate GraphQL
        run: |
          cd test/integrationtest/projecttest && go run -tags graphql main.go && cd ../../../
          git diff --quiet || (echo 'generated go files for graphql are not up to date, check go generate' ; git diff ; exit 1)
      - name: Test
        run: go test -test.count=10 -race -v ./test/integrationtest/... -tags=integration
